container:
  image: node:latest

node_modules_cache: &node_modules_cache
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

# typecheck_task:
#   <<: *node_modules_cache
#   typecheck_script: npm run typecheck

lint_task:
  <<: *node_modules_cache
  lint_script: npm run lint

test_task:
  <<: *node_modules_cache
  test_script: npm test